container_name: {{ cookiecutter.service_name }}
image: {{ cookiecutter.image }}
user: "{{ cookiecutter.uid }}"
network_mode: host
ports:
  - {{ cookiecutter.port }}
volumes:
  - ${PWD}/{{ cookiecutter.service_name }}:/node
entrypoint: /usr/local/bin/crossbar
command:
  - start
  - --personality
  - community
  - --cbdir
  - /node/.crossbar/
